name: Clear Azure Frontend
on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Create Empty
        run:  mkdir "./cleardist" && touch "./cleardist/index.html" && echo "<h1>Empty<h1>" >> "./cleardist/index.html"
        
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ICY_TREE_0DB3A3C03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "./cleardist" 
          skip_app_build: true
          output_location: ''
